### ISSUE TITLE
Parser does not handle reference in external file

### ISSUE THREAD

**Issue by abhijith-prabhakar** [swagger-api/swagger-parser#299]
I am using swagger-codegen(v2.2.1) for java-jaxrs and my file structure is given below
```
|____static
| |____json-schema
| | |____error.json
| | |____error_details.json
| | |____link_description.json
| |____swagger.json
```
swagger.json is referring to error.json which in turn is referring to error_details.json and link_description.json.

In error.json if I provide reference `"$ref":"error_details.json"` swagger codegen cannot find error_details.json and is not working. But, if I provide reference as `"$ref":"./json-schema/link_description.json"` (relative to swagger.json) then codegen works fine, but swagger-ui breaks.

**Comment by diegode** [comment]
@abhijith-prabhakar does it work if you put "./error_details.json" instead of "error_details.json"?

**Comment by abhijith-prabhakar** [comment]
Yes, I have tried it.  It gives below error
```
io.swagger:swagger-codegen-maven-plugin:2.2.1:generate failed: Unable to load RELATIVE ref: ./error_details.json
       	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
       	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
       	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
```

**Comment by diegode** [comment]
Oh, I think this was fixed in https://github.com/swagger-api/swagger-parser/pull/284
This was merged to master after the last release (1.0.22).

**Comment by abhijith-prabhakar** [comment]
I worked with Ron and Tony to test out latest snapshot release of both codegen and parser.  It was not fixed in those as well.  It would nice if someone can double check.

**Comment by diegode** [comment]
Oh, I think I understand why is this happening. This is a bug indeed.

**Comment by abhijith-prabhakar** [comment]
Thanks for checking.  Any ETA on the fix?

**Comment by fehguy** [comment]
Should be fixed now.
